version: "3.7"

services:
    server:
        build:
            context: ./homelab-proxy-manager-server
            target: development-build-stage
        volumes:
            - ./homelab-proxy-manager-server/:/app
            - ./nginx/sites-enabled/:/app/nginx/sites-enabled/
        restart: "unless-stopped"
        networks:
            - backend
        depends_on:
            - nginx
    nginx:
        image: nginx:1.25.3-alpine
        ports:
            - "80:80"
            - "443:443"
        networks:
            - backend
        volumes:
            - ./nginx/sites-enabled/:/etc/nginx/conf.d/
            - ./homelab-proxy-manager-client/dist/spa:/var/www/client

networks:
    backend:
        driver: bridge

volumes:
    database:
