version: "3.7"

services:
    server:
        build:
            context: ./homelab-proxy-manager-server
            target: development-build-stage
        volumes:
            - ./homelab-proxy-manager-server/:/app/homelab-proxy-manager-server
            - ./homelab-proxy-manager-regulator/commands/:/mount/regulator-commands
            # Separate volume for node_modules so that linux depepdencies dont break on windows systems and symlinks work for development
            - node_modules:/app/homelab-proxy-manager-server/node_modules
            - ./nginx/sites-enabled/:/app/nginx/sites-enabled/
        ports:
            - "3000:3000"
        restart: "unless-stopped"
        depends_on:
            - nginx
    nginx:
        container_name: homelab-proxy-manager-nginx
        image: nginx:1.25.3-alpine
        network_mode: "host"
        volumes:
            - ./nginx/sites-enabled/:/etc/nginx/conf.d/
            - ./nginx/certificates/:/etc/nginx/certs/
            - ./homelab-proxy-manager-client/dist/spa:/var/www/client

volumes:
    database:
    node_modules:
