[package]
name = "homelab-proxy-manager-regulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.13", features = ["cargo"] }
notify = "6.1.1"
hex = "*"